-- 用户角色枚举类型
CREATE TYPE user_role_enum AS ENUM ('regular', 'admin');

-- 用户表
CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role user_role_enum NOT NULL DEFAULT 'regular',
  points INTEGER NOT NULL DEFAULT 0,
  is_certified_designer BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  img_path VARCHAR(255),
  bio TEXT DEFAULT ''
);

-- 用户作品表
CREATE TABLE user_works (
  work_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description VARCHAR(200),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_works_user_id
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX idx_user_works_user_id ON user_works (user_id);
CREATE INDEX idx_user_works_created_at ON user_works (created_at DESC);

-- 帖子表
CREATE TABLE posts (
  post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  reply_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_posts_user_id
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX idx_posts_user_id ON posts (user_id);
CREATE INDEX idx_posts_created_at ON posts (created_at DESC);
CREATE INDEX idx_posts_updated_at ON posts (updated_at DESC);

-- 评论表
CREATE TABLE comments (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comments_post_id
    FOREIGN KEY (post_id)
    REFERENCES posts(post_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_comments_user_id
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX idx_comments_post_id ON comments (post_id);
CREATE INDEX idx_comments_user_id ON comments (user_id);
CREATE INDEX idx_comments_created_at ON comments (created_at);

-- 台球杆定制订单表
CREATE TABLE orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  customization_mode VARCHAR(20) NOT NULL DEFAULT 'preset',
  product_name VARCHAR(120) NOT NULL ,
  configuration JSONB ,
  pricing_lines JSONB DEFAULT '[]'::jsonb,
  total_price INTEGER ,
  contact_name VARCHAR(80) NOT NULL,
  contact_phone VARCHAR(30) NOT NULL,
  shipping_address TEXT NOT NULL,
  order_note VARCHAR(500),
  design_image_path VARCHAR(255),
  design_description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'submitted',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user_id
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT chk_orders_customization_mode
    CHECK (customization_mode IN ('preset', 'freeform')),
  CONSTRAINT chk_orders_status
    CHECK (status IN ('submitted', 'processing', 'shipped', 'completed', 'cancelled'))
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_customization_mode ON orders (customization_mode);
CREATE INDEX idx_orders_created_at ON orders (created_at DESC);

-- 邮箱验证码表
CREATE TABLE email_verification_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  code VARCHAR(6) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  ip_address VARCHAR(45),
  user_agent TEXT
);

CREATE INDEX idx_email_verification_codes_email ON email_verification_codes (email);
CREATE INDEX idx_email_verification_codes_expires_at ON email_verification_codes (expires_at);
CREATE INDEX idx_email_verification_codes_created_at ON email_verification_codes (created_at DESC);

-- 用户签到表
CREATE TABLE IF NOT EXISTS user_check_ins (
  check_in_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  check_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  streak_count INTEGER NOT NULL DEFAULT 1,
  base_points INTEGER NOT NULL,
  bonus_points INTEGER NOT NULL DEFAULT 0,
  total_points INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_check_ins_user_id
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT uq_user_check_ins_user_date UNIQUE (user_id, check_in_date),
  CONSTRAINT chk_user_check_ins_streak_count CHECK (streak_count >= 1),
  CONSTRAINT chk_user_check_ins_base_points CHECK (base_points >= 0),
  CONSTRAINT chk_user_check_ins_bonus_points CHECK (bonus_points >= 0),
  CONSTRAINT chk_user_check_ins_total_points CHECK (total_points >= 0)
);

CREATE INDEX IF NOT EXISTS idx_user_check_ins_user_id
  ON user_check_ins (user_id);

CREATE INDEX IF NOT EXISTS idx_user_check_ins_check_in_date
  ON user_check_ins (check_in_date DESC);

-- 通用更新时间戳函数
CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 帖子更新时间戳函数
CREATE OR REPLACE FUNCTION set_posts_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 评论更新时间戳函数
CREATE OR REPLACE FUNCTION set_comments_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 更新帖子回复计数函数
CREATE OR REPLACE FUNCTION update_post_reply_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE posts SET reply_count = reply_count + 1 WHERE post_id = NEW.post_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE posts SET reply_count = GREATEST(reply_count - 1, 0) WHERE post_id = OLD.post_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 清理过期验证码函数
CREATE OR REPLACE FUNCTION cleanup_expired_verification_codes()
RETURNS VOID AS $$
BEGIN
  DELETE FROM email_verification_codes WHERE expires_at < CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql;

-- 各表更新触发器
CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER update_user_works_updated_at
BEFORE UPDATE ON user_works
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER update_posts_updated_at
BEFORE UPDATE ON posts
FOR EACH ROW
EXECUTE FUNCTION set_posts_updated_at_timestamp();

CREATE TRIGGER update_comments_updated_at
BEFORE UPDATE ON comments
FOR EACH ROW
EXECUTE FUNCTION set_comments_updated_at_timestamp();

CREATE TRIGGER update_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

-- 评论计数维护触发器
CREATE TRIGGER trg_update_reply_count_on_insert
AFTER INSERT ON comments
FOR EACH ROW
EXECUTE FUNCTION update_post_reply_count();

CREATE TRIGGER trg_update_reply_count_on_delete
AFTER DELETE ON comments
FOR EACH ROW
EXECUTE FUNCTION update_post_reply_count();

-- 积分记录表（通用版）
CREATE TABLE point_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    points_change INTEGER NOT NULL,          -- 变动数值，正数=获得，负数=消费/扣减
    points_after INTEGER NOT NULL,           -- 变动后的账户余额，用于快速对账
    detail VARCHAR(255) NOT NULL DEFAULT '', -- 变动原因描述，如“签到”“购买枫木前节”
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 约束
    CONSTRAINT chk_points_change_nonzero CHECK (points_change <> 0),
    CONSTRAINT chk_points_after_non_negative CHECK (points_after >= 0),

    -- 外键：保护审计记录，不允许删除仍有积分记录的用户
    CONSTRAINT fk_point_records_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- 索引
CREATE INDEX idx_point_records_user_id ON point_records(user_id);
CREATE INDEX idx_point_records_created_at ON point_records(created_at DESC);
CREATE INDEX idx_point_records_detail ON point_records(detail);   -- 方便按原因筛选

CREATE OR REPLACE FUNCTION sync_user_points_on_point_record()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE users SET points = NEW.points_after WHERE user_id = NEW.user_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_point_records_sync_points
AFTER INSERT ON point_records
FOR EACH ROW
EXECUTE FUNCTION sync_user_points_on_point_record();